#!/usr/bin/python3

import sys

boards = [r.strip().split(',') for r in open(sys.argv[1],'r').readlines() if r[0].isnumeric()]

output = ''

for i in range(len(boards)//9):
    board = [[int(v) for v in r] for r in boards[9*i:9*i+9]]
    for j in range(9):
        row = board[j]
        if sum(row) != 45:
            for k in range(9):
                if row[k] in row[:k]:
                    other = row.index(row[k])
                    col = other if sum([board[n][other] for n in range(9)]) != 45 else k
                    output += str(j*9+col)+','
                    break
    output = output[:-1] + '\n'
output = output[:-1]

with open(sys.argv[2],'w') as file:
    for row in output:
        file.write(row)


